language: objective-c
cache:
  - bundler
  - cocoapods
rvm: 2.4.3
matrix:
    include:
        - osx_image: xcode9.4
          env: PLATFORM=iOS
          script:
            make test
            make test DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=10.3.1"
            make test DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=9.3"
        - osx_image: xcode9.4
          env: PLATFORM=tvOS
          script: make test
install: make bootstrap

before_deploy: headerdoc2html -o docs Source -j; gatherheaderdoc docs; mv docs/masterTOC.html docs/index.html

deploy:
  provider: pages
  local_dir: docs # only include the contents of the generated docs dir
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in travis-ci dashboard
  on:
    tags: true # only deploy when tag is applied to commit
